version: '3.8'

networks:
  dev:
    driver: bridge

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./logs:/var/log/nginx
    depends_on:
      - frontend
      - backend
    networks:
      - dev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://backend:3001
    networks:
      - dev
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    image: node:alpine
    working_dir: /usr/src/app
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
      - ./db.json:/usr/src/app/db.json
    command: sh -c "npm install && npm run dev"
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
    networks:
      - dev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/todos"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  db_data: