name: Deploy to AWS EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -ex  # Exit on error and print commands

            # Install required packages
            sudo yum update -y
            sudo yum install -y git docker firewalld curl wget

            # Configure firewall
            echo "Configuring firewall..."
            sudo systemctl start firewalld
            sudo systemctl enable firewalld
            sudo firewall-cmd --permanent --add-port=80/tcp
            sudo firewall-cmd --permanent --add-port=3000/tcp
            sudo firewall-cmd --permanent --add-port=3001/tcp
            sudo firewall-cmd --reload

            # Install Docker Compose
            echo "Installing Docker Compose..."
            DOCKER_COMPOSE_VERSION=$(curl -s https://api.github.com/repos/docker/compose/releases/latest | grep 'tag_name' | cut -d\" -f4)
            sudo curl -L "https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose

            # Start and enable Docker
            sudo systemctl start docker
            sudo systemctl enable docker
            sudo usermod -aG docker $USER

            # Configure Git credentials
            git config --global credential.helper store
            echo "https://${{ secrets.GH_TOKEN }}@github.com" > ~/.git-credentials

            # Setup application directory
            APP_DIR=~/RTK-Query
            echo "Deploying to $APP_DIR"

            # Remove existing directory if corrupted
            if [ -d "$APP_DIR" ] && [ ! -d "$APP_DIR/.git" ]; then
              echo "Removing invalid repository..."
              rm -rf "$APP_DIR"
            fi

            # Clone or update repository
            if [ ! -d "$APP_DIR" ]; then
              echo "Cloning fresh repository..."
              git clone https://${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git "$APP_DIR"
            else
              echo "Updating existing repository..."
              cd "$APP_DIR"
              git fetch origin
              git reset --hard origin/main
            fi

            # Verify repository and files
            cd "$APP_DIR"
            ls -la

            if [ ! -f "docker-compose.yml" ]; then
              echo "Error: docker-compose.yml not found!"
              exit 1
            fi

            # Stop any running services and clear ports
            echo "Cleaning up existing services..."
            sudo systemctl stop nginx || true  # Stop system nginx if running
            sudo lsof -ti:80 | xargs -r sudo kill -9 || true  # Force kill anything on port 80
            docker-compose down --remove-orphans || true  # Stop existing containers

            # Verify port availability
            if sudo lsof -i :80; then
              echo "Error: Port 80 is still in use"
              exit 1
            fi

            # Verify network configuration
            echo "Checking network configuration..."
            sudo netstat -tulpn
            curl -v localhost:80 || true

            # Deploy with enhanced logging
            cd "$APP_DIR"
            echo "Starting deployment from $(pwd)"
            docker-compose config
            docker-compose pull
            docker-compose up --build -d

            # Enhanced verification
            echo "Deployment verification:"
            docker-compose ps
            docker ps -a
            docker network ls
            docker-compose logs

            # Test external access
            echo "Testing external access:"
            curl -v http://localhost:80
            curl -v http://$(curl -s http://169.254.169.254/latest/meta-data/public-ipv4):80
