name: Deploy Fullstack App to AWS (CloudFormation, EC2, ECR, S3, CloudFront)

on:
  push:
    branches: [main]

jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Delete failed CloudFormation stack (if in ROLLBACK state)
        run: |
          STATUS=$(aws cloudformation describe-stacks --stack-name secret-domain-net-stack --region eu-north-1 --query "Stacks[0].StackStatus" --output text || echo "NOT_FOUND")
          if [[ "$STATUS" == "ROLLBACK_IN_PROGRESS" || "$STATUS" == "ROLLBACK_COMPLETE" ]]; then
            echo "Deleting failed stack secret-domain-net-stack..."
            aws cloudformation delete-stack --stack-name secret-domain-net-stack --region eu-north-1
            aws cloudformation wait stack-delete-complete --stack-name secret-domain-net-stack --region eu-north-1
          else
            echo "No failed stack to delete. Current status: $STATUS"
          fi
      - name: Deploy CloudFormation stack
        run: |
          aws cloudformation deploy \
            --template-file infrastructure.yml \
            --stack-name secret-domain-net-stack \
            --capabilities CAPABILITY_NAMED_IAM \
            --region eu-north-1

      - name: Attach OAC to CloudFront origin
        run: |
          # Set variables
          STACK_NAME=secret-domain-net-stack
          REGION=${{ secrets.AWS_REGION }}
          OAC_NAME=OAC-SecretDomainNet

          # Get CloudFront Distribution ID from stack outputs
          CF_ID=$(aws cloudformation describe-stacks \
            --stack-name $STACK_NAME \
            --region $REGION \
            --query "Stacks[0].Outputs[?OutputKey=='CloudFrontDistributionId'].OutputValue" \
            --output text)

          # Try to get existing OAC ID
          OAC_ID=$(aws cloudfront list-origin-access-controls \
            --region $REGION \
            --query "OriginAccessControlList.Items[?OriginAccessControlName=='$OAC_NAME'].Id" \
            --output text)

          # Only create if not found
          if [ -z "$OAC_ID" ] || [ "$OAC_ID" == "None" ]; then
            OAC_ID=$(aws cloudfront create-origin-access-control \
              --region $REGION \
              --origin-access-control-config '{
                "Name": "'"$OAC_NAME"'",
                "Description": "OAC for secret-domain-net-frontend",
                "SigningProtocol": "sigv4",
                "SigningBehavior": "always",
                "OriginAccessControlOriginType": "s3"
              }' \
              --query 'OriginAccessControl.Id' \
              --output text)
          fi

          # Get current distribution config and ETag
          aws cloudfront get-distribution-config --id $CF_ID --region $REGION > dist.json
          ETag=$(jq -r '.ETag' dist.json)
          jq '.DistributionConfig.Origins.Items[0].OriginAccessControlId = "'$OAC_ID'"' dist.json > new-dist.json

          # Remove ETag and DistributionConfig from new-dist.json for update
          jq '.DistributionConfig' new-dist.json > config.json

          # Update distribution to use OAC
          aws cloudfront update-distribution \
            --id $CF_ID \
            --if-match $ETag \
            --distribution-config file://config.json \
            --region $REGION
      - name: Show CloudFormation stack events
        if: failure()
        run: |
          echo "Showing stack events for secret-domain-net-stack..."
          aws cloudformation describe-stack-events --stack-name secret-domain-net-stack --region eu-north-1
  build-backend:
    runs-on: ubuntu-latest
    needs: [deploy-infrastructure]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:latest ./backend

      - name: Remove all ECR images
        run: |
          IMAGE_IDS=$(aws ecr list-images \
            --repository-name ${{ secrets.ECR_REPOSITORY }} \
            --region ${{ secrets.AWS_REGION }} \
            --query 'imageIds[*]' \
            --output json)
          if [ "$IMAGE_IDS" != "[]" ]; then
            aws ecr batch-delete-image \
              --repository-name ${{ secrets.ECR_REPOSITORY }} \
              --region ${{ secrets.AWS_REGION }} \
              --image-ids "$IMAGE_IDS"
          else
            echo "No images to delete."
          fi

      - name: Push Docker image to ECR
        run: |
          docker push ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:latest

  deploy-backend:
    runs-on: ubuntu-latest
    needs: [build-backend]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Write SSH key to file
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > /tmp/ec2_key.pem
          chmod 600 /tmp/ec2_key.pem

      - name: Copy docker-compose.yml and nginx.conf to EC2
        run: |
          scp -i /tmp/ec2_key.pem -o StrictHostKeyChecking=no backend/docker-compose.yml backend/nginx.conf ec2-user@${{ secrets.EC2_HOST }}:~/
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          timeout: 30m
          envs: AWS_ACCESS_KEY_ID,AWS_SECRET_ACCESS_KEY,AWS_REGION,BACKEND_ENV,ECR_REGISTRY,ECR_REPOSITORY
          script: |
            export AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}"
            export AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}"
            export AWS_REGION="${{ secrets.AWS_REGION }}"
            set -exuo pipefail
            sudo yum install -y docker
            sudo systemctl start docker
            sudo systemctl enable docker
            sudo usermod -aG docker ec2-user

            # Install docker-compose
            sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose

            # Login to ECR
            aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | sudo docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}

            cd ~/

            # Set up environment variables
            echo "${{ secrets.BACKEND_ENV }}" > .env

            # Clean up unused Docker resources
            sudo docker system prune -af


            # Pull latest image and start containers
            export BACKEND_IMAGE=${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:latest
            echo "BACKEND_IMAGE=$BACKEND_IMAGE"
            sudo -E docker-compose pull
            sudo -E docker-compose up -d

            # Health check
            curl -v http://localhost:80 || true

  build-frontend:
    runs-on: ubuntu-latest
    needs: [deploy-backend]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies and build
        working-directory: ./frontend
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
        run: |
          npm install
          npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to S3
        run: |
          aws s3 sync ./frontend/dist s3://secret-domain-net-frontend --delete

      - name: Log S3 bucket Website endpoint URL
        run: |
          echo "( CloudFront URL with domain name ) S3 Website endpoint URL: https://secret-domain.net/"
          aws s3 ls s3://secret-domain-net-frontend

  invalidate-cloudfront:
    runs-on: ubuntu-latest
    needs: [build-frontend]
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Get CloudFront Distribution ID from CloudFormation
        id: get_cf_id
        run: |
          CF_ID=$(aws cloudformation describe-stacks \
            --stack-name secret-domain-net-stack \
            --region ${{ secrets.AWS_REGION }} \
            --query "Stacks[0].Outputs[?OutputKey=='CloudFrontDistributionId'].OutputValue" \
            --output text)
          echo "CLOUDFRONT_DISTRIBUTION_ID=$CF_ID" >> $GITHUB_ENV

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
