name: Deploy to AWS EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Install required packages
            sudo yum update -y
            sudo yum install -y git docker

            # Start and enable Docker
            sudo systemctl start docker
            sudo systemctl enable docker

            # Fix Docker permissions
            sudo usermod -aG docker $USER
            sudo chmod 666 /var/run/docker.sock

            # Install Docker Compose
            if ! command -v docker-compose &> /dev/null; then
              sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
            fi

            # Clone or pull repository
            if [ ! -d "~/RTK-Query" ]; then
              git clone https://github.com/yourusername/RTK-Query.git ~/RTK-Query
            else
              cd ~/RTK-Query
              git pull
            fi

            # Deploy application
            cd ~/RTK-Query
            sudo docker-compose down
            sudo docker-compose up --build -d

            # Clean up
            sudo docker image prune -f
