name: Deploy to AWS EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Update system and install dependencies
            sudo yum update -y
            sudo yum install -y git docker

            # Configure Docker
            sudo systemctl start docker
            sudo systemctl enable docker
            sudo usermod -aG docker $USER
            newgrp docker

            # Install Docker Compose
            DOCKER_COMPOSE_VERSION=$(curl -s https://api.github.com/repos/docker/compose/releases/latest | grep 'tag_name' | cut -d\" -f4)
            sudo curl -L "https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose

            # Setup application directory
            APP_DIR=~/RTK-Query
            if [ ! -d "$APP_DIR" ]; then
              git clone https://github.com/${GITHUB_REPOSITORY}.git $APP_DIR
            else
              cd $APP_DIR
              git fetch --all
              git reset --hard origin/main
            fi

            # Deploy using Docker Compose
            cd $APP_DIR
            docker-compose down
            docker-compose pull
            docker-compose up --build -d

            # Deploy using Docker Compose
            docker-compose down || true
            docker-compose pull
            docker-compose up --build -d

            # Show deployment status
            echo "Docker Compose Status:"
            docker-compose ps
            echo "Docker Logs:"
            docker-compose logs
