name: Deploy to AWS EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e  # Exit on any error

            # Update system and install dependencies
            sudo yum update -y
            sudo yum install -y git docker

            # Configure Docker
            sudo systemctl start docker
            sudo systemctl enable docker
            sudo usermod -aG docker $USER

            # Install Docker Compose
            DOCKER_COMPOSE_VERSION=$(curl -s https://api.github.com/repos/docker/compose/releases/latest | grep 'tag_name' | cut -d\" -f4)
            sudo curl -L "https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose

            # Setup and verify application directory
            APP_DIR=~/RTK-Query
            echo "Deploying to $APP_DIR"

            # Clone or update repository
            if [ ! -d "$APP_DIR" ]; then
              echo "Cloning repository..."
              git clone https://github.com/${GITHUB_REPOSITORY}.git $APP_DIR
            else
              echo "Updating existing repository..."
              cd $APP_DIR
              git fetch --all
              git reset --hard origin/main
            fi

            # Verify docker-compose.yml exists
            cd $APP_DIR
            if [ ! -f "docker-compose.yml" ]; then
              echo "Error: docker-compose.yml not found in $(pwd)"
              ls -la
              exit 1
            fi

            # Deploy application
            echo "Starting deployment with Docker Compose..."
            docker-compose down || true
            docker-compose pull
            docker-compose up --build -d

            # Verify deployment
            echo "Checking deployment status..."
            docker-compose ps
            docker ps -a
            docker-compose logs
